Module1 task3
htmlacademy-ecmascript/2100191-cinemaddict-18 pull request #3
Opened 2022-08-12 16:15 UTC by ArthurSkorzeny

2022-08-12 17:52 UTC, ArtMan-8 requested changes

2022-08-12 17:52 UTC, ArtMan-8 commented on src/main.js
> +render( new UserProfileView(), siteHeaderElement);
Пробелы лишние после открытия скобки.
Можно редактор настроить, что-бы редактор при сохранении файлов сразу форматировал их.

2022-08-12 17:52 UTC, ArtMan-8 commented on src/presenter/films-presenter.js
> +  filmsComponent = new FilmsView();
А инициализации значений разве не должна быть в конструкторе7

2022-08-12 17:52 UTC, ArtMan-8 commented on src/presenter/films-presenter.js
> +    for (let i = 0; i < 5; i++) {
Что за `5`? магическое значение

2022-08-12 20:20 UTC, ArthurSkorzeny commented
Строчки инициализации значений делал по демо-проекту, сейчас я не очень понимаю, как это можно поменять, но в будущем углубляясь в тему, я переделаю

2022-08-13 11:46 UTC, ArtMan-8 approved these changes

2022-08-13 11:47 UTC, merged